### PR TITLE
Files dashboard

### PR DESCRIPTION
**Pull request by ciara-mc**

### CODE REVIEW

**Comment by dan-tang-ssd** [comment]
Pulled latest code to local env, then performed testing with below result.
Looks like some minor refinements are required.

Files CRUD panel, list view
- Show uploader name instead of uploader ID
- is_legacy, is_success checkboxes not showed

Files CRUD panel, preview view
 - is_legacy, is_success values not showed


Files table in local database:
image

image

image

**Comment by dave-mills** [comment]
This looks great! I think we have 2 things left to add here from our discussion on Tuesday: 
- a way for users to download the file. (I'd suggest using a [wrapper](https://backpackforlaravel.com/docs/5.x/crud-columns#custom-wrapper-for-columns) on the file name (or original file name, as the "name" field isn't in the main list view). 
- a way to sort the list by original name to show the duplicate uploads.

**Comment by dan-tang-ssd** [comment]
Hi Ciara, the columns showed in Stations CRUD panel and Files CRUD panel look good.

I manually entered original filename in backend database, tried to download file but failed. Is it success at your side?

image

image

image

**Comment by dan-tang-ssd** [comment]
As Dave advised, I did below and now it works fine.
1. Run command "php artisan storage:link"
2. Move data files into folder C:\public\ws\storage\app\public\rawfiles

image

image

image

**Comment by dan-tang-ssd** [comment]
Added below items:
1. files table, add two new columns: is_marked_as_reviewed, is_marked_to_remove
2. Files CRUD panel, show two newly added columns
3. Files CRUD panel, add filters for two newly added columns
4. Files CRUD panel, add "Mark as Reviewed" button, disable button if this file has been marked as reviewed
5. Files CRUD panel, add "Mark to Remove" button, disable button if this file has been marked to remove

image

image

Questions:
 1. After clicking "Mark as Reviewed" or "Mark to Remove" button, it refreshes to page 1 now. Is it possible to refresh to a particular page? e.g. page 3 first record, mark it as reviewed, refreshed to page 1 now, can we show page 3 after refresh?
 2. is it possible to refresh only one row in a CRUD panel?

**Comment by dave-mills** [comment]
Good questions... 
>    After clicking "Mark as Reviewed" or "Mark to Remove" button, it refreshes to page 1 now. Is it possible to refresh to a particular page? e.g. page 3 first record, mark it as reviewed, refreshed to page 1 now, can we show page 3 after refresh?
>    is it possible to refresh only one row in a CRUD panel?

Quite possibly, by accessing the datatables api directly... 

https://datatables.net/reference/api

**Comment by dan-tang-ssd** [comment]
Dave, Thank you for your suggestions.

I have revised columns ordering and show mark and unmark buttons in different colors. (To be refined for a better color scheme if necessary)

image

Regarding two flag columns, your suggestion can provide clearer meaning to users.
User should review each record, and tell us whether it is marked to keep OR remove.
Suppose we cannot both keep and remove the same record, we need user to check if this occurs.
If there are records not marked to keep and not marked to remove, that means user not yet review this record.

I am going to modify based on this approach, it will be ready for testing soon.

**Comment by dan-tang-ssd** [comment]
Refinements completed:
1. Files CRUD panel, change column name from is_marked_as_reviewed to is_marked_to_keep
2. Files CRUD panel, show mark and unmark buttons in different colors
3. Files CRUD panel, hide observiation_id column, group flag columns and buttons together in front end

image

image

**Comment by dave-mills** [comment]
Great! Looks good to me. I'd say this is ready to merge into dev + check on the staging site. From memory, the staging site and live site both thave the full set of re-uploaded files and data, so we can review this on staging and then publish to live pretty confidently.

**Comment by dan-tang-ssd** [comment]
Hi Dave,

I drafted and tested below SQL to fill in value for column files.original_name.

P.S. There are a few files has been renamed by UMSA. These filenames will not have timestamp as prefix.


-- find UMSA renamed files for clarity
select name, original_name from files where name not like '1%';

update files set original_name = name where name not like '1%';


-- find files that UMSA not renamed
select name, original_name from files where name like '1%';

select name, original_name, substring(name, 12) from files where name like '1%';

update files set original_name = substring(name, 12) where name like '1%';

**Comment by dan-tang-ssd** [comment]
Hi Dave,

I have updated column files.original_name in staging database with below SQLs:


-- find files that UMSA not renamed
-- 220 records
select id, name, substring(name, 12), original_name from files where name like '15%' or name like '16%' order by id;

update files set original_name = substring(name, 12) where name like '15%' or name like '16%';


-- find files that UMSA renamed
-- 142 records
select id, name, name, original_name from files where name not like '15%' and name not like '16%' order by id;

update files set original_name = name where name not like '15%' and name not like '16%';


-- find records without original_name
-- 0 record
select name, original_name from files where original_name is null;


-- manual update for files with double timestamp prefix
-- 5 records
select id, name, substring(original_name, 12), original_name from files where id in (1148,1168,1169,1170,1171);

update files set original_name = substring(original_name, 12) where id in (1148,1168,1169,1170,1171);


-- visual check
select id, name, original_name from files;

**Pull request merged**
