### PR TITLE
Gen summary met data

### PR DESCRIPTION
**Pull request by dan-tang-ssd**
Short term workaround to re-generate all summary met data daily at midnight, and some minor fixes.

### CODE REVIEW

**Comment by dave-mills** [comment]
Looks good - running the new combined procedure localy took about 2m30, processing the 1.6 million met_data records I have (I took a clone of the live data a while back to use for local testing). 

Question - if I leave my computer on overnight, the event should trigger to reprocess the data locally, correct? (I've never used MySQL events before!).

**Comment by dan-tang-ssd** [comment]
> Question - if I leave my computer on overnight, the event should trigger to reprocess the data locally, correct? (I've never used MySQL events before!).

Yes, exactly.

You may change the frequency from 1 day to 1 hour or 10 minutes for local testing.
Please note that the event will not trigger before the defined period of time passed.
e.g. create a schedule job to run every 10 minutes at 3:55pm. The first execution will take place at 4:10pm instead of 4:00pm.

**Comment by dan-tang-ssd** [comment]
> Looks good - runs nicely locally, although I was getting a few non-breaking Javascript errors when testing the upload, which were related to occasions then the `selectedUnit###` did not have `value` props set. See my inline comments for a possible solution.

Um.... there is no Javascript error in my local testing... Would you share how to replicate these errors?

image

**Comment by dave-mills** [comment]
> Yes, exactly.

> You may change the frequency from 1 day to 1 hour or 10 minutes for local testing.
> Please note that the event will not trigger before the defined period of time passed.
> e.g. create a schedule job to run every 10 minutes at 3:55pm. The first execution will take place at 4:10pm instead of 4:00pm.

Ahh, I think I understand. So, with the event as-is, it won't run at all for 1 day, and then will run every midnight, because that was the `start` time. (So e.g. if I left it running now, it would not run tonight, but would run on Tusday night at midnight.)

Just had a quick play with the frequency locally. Nice to know how to setup these sort of commands direclty in SQL!

**Comment by dan-tang-ssd** [comment]
Thank you Dave, I can replicate the Javascript errors now.

We need to check null value for both this.selectedUnitTemp and this.selectedUnitTemp.value.

I hope to make it simpler in one line but it seems not quite possible... Is it feasible to write something like below?
`formData.append('selectedUnitTemp', this.selectedUnitTemp OR this.selectedUnitTemp.value ?? 'ºC');`

I have further refined code to handle it, but it looks harder to read, just similar as before...

**Comment by dan-tang-ssd** [comment]
Thank you Dave. The clearable property of v-select works well.
User can no longer clear the value in selection box now. (The little cross goes away)

I have revised and tidied up code for this.

image

**Review by dave-mills — APPROVED** [review]
👍  Looks good to me - this is ready to merge to dev, and I think deploy to live after confirming that the events run smoothly on staging. (Given it's not a major rewrite of anything, I don't think we need to do too much detailed testing of staging). 

Thanks!

**Comment by dan-tang-ssd** [comment]
Merged this PR into branch dev.
Staging env updated automatically as "Quick Deploy" is enabled.

Perform checking after merging:
1. Database stored procedure "generate_all_summary_met_data" created
2. Database event event_recurring_generate_all_summary_met_data created
3. Data upload page, vue 3 component, unit selection box

TODO:
1. Check whether summary met data records re-generated on 2022-05-28

Hit [F5] in browser, vue 3 component not updated, user still cannot select unit.
Hit [Ctrl] + [Shift] + [R] in browser, vue 3 component updated, user can select unit.
Probably the vue 3 component is cached in browser, not sure whether we can force the browser to load the latest vue 3 component.

image

image

image

**Pull request merged**
