### PR TITLE
Data Upload Refinements

### PR DESCRIPTION
**Pull request by dan-tang-ssd**
I created this PR to record my testing result for latest code in branch "dev".

For file Kernal.php, I added a space as a dummy change for creating a pull request.
Actually there is no program change when I create this PR.
I will revert and push it after creating this PR.

### CODE REVIEW

**Comment by dan-tang-ssd** [comment]
I have executed "npm run dev" and refresh browser many times... I hope to force my browser to load latest compiled vue component....

Total number of records uploaded in PROGRESS

There are 10 records in data file, but it shows that there are 11 records uploaded in PROGRESS.

image

**Comment by dan-tang-ssd** [comment]
In confrirmation panel:
- When user click "Cancel" button, met_data_preview records are removed.
 - When user click "Confirm" button, met_data_preview records are kept and copied to met_data.

For traceability and consistency, program should not remove met_data_preview records at all.

We should standardize to remove met_data_preview records by daily schedule job, e.g. remove met_data_preview records older than 14 days

**Comment by dave-mills** [comment]
> For traceability and consistency, program should not remove met_data_preview records at all.

> We should standardize to remove met_data_preview records by daily schedule job, e.g. remove met_data_preview records older than 14 days.

> - Should we disable "Confirm" button when there is no new records in the uploaded file?
> - When there is no new record to add to database, user click "Confirm" button, a daily_met_data record with current date is generated.


> When user has not tick "I confirm" checkbox, user still can click "Confirm" button.
> - Should we enable/disable "Confirm" button when user tick/untick "I confirm" checkbox?
> - Should we add a space between the checkbox and "I confirm" label for better readability?

Yes to all comments / questions :) 


### 11 / 10 uploaded
> There are 10 records in data file, but it shows that there are 11 records uploaded in PROGRESS.

Interesting! Is this reproducible? I assumed this was a caching of old code issue, but it sounds like you're definitely running the latest compiled Vue component... 

I have an idea as to what is causing it; I suspect it's because the DavisFileImport model funciton isn't actually returning anything, which is probably causing some issues with the job queuing... I'll submit a seperate fix for this, which should also make the job queue more stable long term.

**Comment by dan-tang-ssd** [comment]
> It would be good to find any possible columns which require unit conversion by referring to data definition document provided by Edwin.

Checked data definition document provided by Edwin. There is no new column requires unit conversion.
I have also highlighted items in data defintiion document FYI.

[EXPLICACIÓN DE LAS VARIABLES DAVIS_English_For_Crosschecking.docx](https://github.com/stats4sd/red-de-redes/files/9085516/EXPLICACION.DE.LAS.VARIABLES.DAVIS_English_For_Crosschecking.docx)

**Comment by dan-tang-ssd** [comment]
> Interesting! Is this reproducible? I assumed this was a caching of old code issue, but it sounds like you're definitely running the latest compiled Vue component...

Yes, it is reproducible.
I can repeat this in my normal browser Firefox.

I just did a testing in Google Chrome which I seldom used for testing. I got same result...

Firefox:
image

Google Chrome:
image

**Comment by dan-tang-ssd** [comment]
A very minor thing found when there are two browsers (browser 1 and browser 2) opened for data upload page.
When I perform data upload in browser 1, the same notiification will appear in both browser 1 and browser 2.
Both browser 1 and browser 2 will show preview panel for user confirmation.

I think it is not likely to have two browsers opening data upload page on the same computer.
Unless the user has so many files to be uploaded (um.... I hope UMSA will not upload history data files in this way...)

I do not think we need to fix this.
Just to mark it down here for reference and we know what is happening in case user report this.

Browser 1, before upload
image

Browser 2, before upload
image

Browser 1, after upload
image

Browser 2, after upload
image

**Comment by dave-mills** [comment]
> A very minor thing found when there are two browsers (browser 1 and browser 2) opened for data upload page.
> When I perform data upload in browser 1, the same notiification will appear in both browser 1 and browser 2.
> Both browser 1 and browser 2 will show preview panel for user confirmation.

Mmm, this is because the events are being broadcast on a per-user channel - and the page is listening to that user channel, so every event is heard by every page. It'd be a relatively quick fix to instead have a channel per upload_id, but I agree this is not a required fix.

**Comment by dan-tang-ssd** [comment]
It would be very helpful for tracing if we have some more details in files table:

1. Fill in file upload date time to columns created_at and updated_at
2. Add new columns min_fecha and max_fecha for minimum date time and maximum date time found in the uploaded met data file

image

**Comment by dave-mills** [comment]
>It would be very helpful for tracing if we have some more details in files table:

>    Fill in file upload date time to columns created_at and updated_at


I'm surprised created_at  and updated_at isn't filled in the live database - it's completed in my local version, so I wonder what is causing them to remain NULL in live: Screenshot 2022-07-12 at 10 21 40

>    Add new columns min_fecha and max_fecha for minimum date time and maximum date time found in the uploaded met data file

Good idea with the min + max dates. Should be easy to add after the import.

**Comment by dan-tang-ssd** [comment]
> > It would be very helpful for tracing if we have some more details in files table:
> 
> > Fill in file upload date time to columns created_at and updated_at
> 
> I'm surprised created_at and updated_at isn't filled in the live database - it's completed in my local version, so I wonder what is causing them to remain NULL in live: Screenshot 2022-07-12 at 10 21 40
> 
> > Add new columns min_fecha and max_fecha for minimum date time and maximum date time found in the uploaded met data file
> 
> Good idea with the min + max dates. Should be easy to add after the import.

Just did a checking on local db, staging db and live db.
Columns files.created_at and files.updated_at are filled with values.
Those files records without value in columns created_at and updated_at are "bulk-reupload"...

image

**Comment by dan-tang-ssd** [comment]
Perform testing in local env regarding generating summary met data:

Related tables are empty before each testing, tables including:
met_data, met_data_preview, daily_met_data, tendays_met_data, monthly_met_data, yearly_met_data

It looks like most processing time is spent on calculating daily met data.
Calculating tendays, monthly, yearly met data do not take much time.

```
No.		No. of Records		Time (ms)		Daily	Tendays	Monthly	Yearly
==================================================================================================
1		10			8			Y	N	N	N
2		10			50			Y	Y	Y	Y
3		8063			511			Y	N	N	N
4		8063			571			Y	Y	Y	Y
```

**Comment by dan-tang-ssd** [comment]
For data upload vue component, just added a feature to disable "Confirm" button when:
1. The uploaded file does not contain any new record OR
2. The uploaded file contains some existing records and some new records, i.e. scenario 3. And user has not ticked the confirmation checkbox yet

**Pull request merged**
